name: 'Discord Alarm'
on: push

jobs:
  webhook:
    name: 'WEBHOOK'
    runs-on: 'ubuntu-latest'
    
    steps:
    - uses: actions/checkout@v3

    - name: pwd
      id: message
      shell: bash
      run: |
        echo "STEP_VALUE=$(git log --pretty=format:"%s" -1)" >> $GITHUB_OUTPUT
    
    - name: Send a message to Discord
      shell: bash
    
      run: |
       curl -X POST https://discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/${{ secrets.WEBHOOK_TOKEN }} \
       -H 'Content-type: application/json' \
       -d '{
          "content": "${{ steps.message.outputs.STEP_VALUE }}"
        }'
